# Generated by Django 5.0.3 on 2024-05-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resortapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('I rather not say!', 'I rather not say!')], max_length=20)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contacts',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
