# Generated by Django 5.0.3 on 2024-06-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resortapp', '0003_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='password',
        ),
    ]
