# Generated by Django 5.0.3 on 2024-06-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resortapp', '0004_remove_members_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateField()),
                ('payment_type', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
